theme: jekyll-theme-minimal
title: Senior Design Templates and Tutorials
description: Contains templates for proposal and final report; samples for proposal, final report, and presentations; contains various tutorials.  
